"""init

Revision ID: e218ea87da36
Revises: 
Create Date: 2022-08-02 20:47:00.368634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e218ea87da36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('iso_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('iso_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('avg_temp', sa.Float(), nullable=True),
    sa.Column('daily_chance_of_rain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.iso_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'date', name='ui_primarykey_citydate')
    )
    op.create_table('travels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('weather_forecast_origin_id', sa.String(), nullable=True),
    sa.Column('weather_forecast_destination_id', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('datetime_departure', sa.DateTime(), nullable=True),
    sa.Column('datetime_arrival', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weather_forecast_destination_id'], ['weather_forecast_days.id'], ),
    sa.ForeignKeyConstraint(['weather_forecast_origin_id'], ['weather_forecast_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travels')
    op.drop_table('weather_forecast_days')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
